name: qr_ipfs
description: Mobile app that loads the QR-IPFS SPA offline
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.7"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.13.0 
  webview_flutter_android: ^4.10.5
  permission_handler: ^12.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - docs/
